package nl.tudelft.oopp.demo.entities;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Abstract Model.
 * This model defines the default property, which all tables should have
 * This includes: ID
 * All (Database) models should extend this Model
 */
@MappedSuperclass
public class AbstractModel {

    /**
     * AutoGenerated Id that every entity will have.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
